export const attributesCasing = [
  {
    id: 0,
    type: 'Input',
    label: 'stratigraphy_name',
    value: '',
    require: true,
    isNumber: true,
  },
  {
    id: 1,
    type: 'Dropdown',
    label: 'Kind',
    value: '',
    require: true,
    schema: '',
    multiple: false,
    search: false,
  },
  {
    id: 2,
    type: 'Input',
    label: 'elevationCasing',
    value: '',
    require: true,
    isNumber: true,
  },
  {
    id: 3,
    type: 'Dropdown',
    label: 'refElecationCasing',
    value: '',
    require: true,
    schema: '',
    multiple: false,
    search: false,
  },
  {
    id: 4,
    type: 'Date',
    label: 'dateSpud',
    value: '',
  },
  // {
  //   id: 5,
  //   type: 'Date',
  //   label: 'dateFinish',
  //   value: '',
  // },
  // {
  //   id: 6,
  //   type: 'Date',
  //   label: 'dateAbandonment',
  //   value: '',
  // },
  // {
  //   id: 7,
  //   type: 'Input',
  //   label: 'remarks',
  //   value: '',
  //   require: true,
  //   isNumber: true,
  // },
];
